# Generated by Django 2.1.2 on 2018-10-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_avaliacao_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='nota',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
