# Generated by Django 2.1.2 on 2018-10-09 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0003_avaliacao_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
